apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: goreview
  description: |
    Go linter with Einride standard rules not already covered by open source linters
  annotations:
    github.com/project-slug: einride/goreview
    github.com/team-slug: einride/team-cloud-control
    backstage.io/source-location: url:https://github.com/einride/goreview/tree/master/
spec:
  type: library
  lifecycle: production
  owner: team-cloud-control
