steps:
  - name: gcr.io/einride/cloud-builder:1.15
    args: ["/cloud-builder/git-init.sh"]
    env:
      - REPO_NAME=$REPO_NAME
      - COMMIT_SHA=$COMMIT_SHA

  - name: gcr.io/einride/cloud-builder:1.15
    args: ["make"]
