on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://golangci/golangci-lint:v1.30.0
        with:
          args: golangci-lint run
        env:
          CGO_ENABLED: 0
