on: [push]

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "1.15"

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - run: make
